<!DOCTYPE html>
<html>
<head>
    <title>Document Report - {{ $document->document_number }}</title>
    <style>
        @page {
            size: A4;
            margin: 2cm;
        }
        body {
            font-family: Arial, sans-serif;
            font-size: 11pt;
            line-height: 1.6;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 3px solid #2563eb;
            padding-bottom: 15px;
        }
        .header h1 {
            margin: 0;
            color: #2563eb;
            font-size: 24pt;
        }
        .header p {
            margin: 5px 0 0 0;
            color: #666;
            font-size: 10pt;
        }
        .section {
            margin-bottom: 25px;
        }
        .section h2 {
            color: #2563eb;
            font-size: 16pt;
            margin-bottom: 15px;
            border-bottom: 2px solid #e5e7eb;
            padding-bottom: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background-color: #2563eb;
            color: white;
            padding: 10px;
            text-align: left;
            font-weight: bold;
            border: 1px solid #1e40af;
        }
        td {
            padding: 10px;
            border: 1px solid #d1d5db;
        }
        tr:nth-child(even) {
            background-color: #f9fafb;
        }
        .info-table th {
            background-color: #f3f4f6;
            color: #333;
            width: 35%;
        }
        .info-table td {
            background-color: white;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 9pt;
            color: #666;
            border-top: 1px solid #e5e7eb;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Document Report</h1>
        <p>Generated on: {{ now()->format('F d, Y h:i A') }}</p>
    </div>
    
    <div class="section">
        <h2>Document Information</h2>
        <table class="info-table">
            <tr>
                <th>Document Title</th>
                <td>{{ $document->title }}</td>
            </tr>
            <tr>
                <th>Document #</th>
                <td>{{ $document->document_number }}</td>
            </tr>
            <tr>
                <th>Current Location Department</th>
                <td>{{ $document->department ? $document->department->name : 'N/A' }}</td>
            </tr>
            <tr>
                <th>Document Type</th>
                <td>{{ $document->document_type }}</td>
            </tr>
            <tr>
                <th>Created By</th>
                <td>{{ $document->creator ? $document->creator->name : 'Unknown' }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ $document->status }}</td>
            </tr>
            <tr>
                <th>Created Date</th>
                <td>{{ $document->created_at->format('F d, Y h:i A') }}</td>
            </tr>
            @if($document->description)
            <tr>
                <th>Description</th>
                <td>{{ $document->description }}</td>
            </tr>
            @endif
        </table>
    </div>
    
    <div class="section">
        <h2>Document History</h2>
        @if($document->statusLogs->count() > 0)
        <table>
            <thead>
                <tr>
                    <th>Date & Time</th>
                    <th>Old Status</th>
                    <th>New Status</th>
                    <th>Updated By</th>
                    <th>Remarks</th>
                </tr>
            </thead>
            <tbody>
                @foreach($document->statusLogs as $log)
                <tr>
                    <td>{{ $log->created_at->format('M d, Y h:i A') }}</td>
                    <td>{{ $log->old_status ?? 'N/A' }}</td>
                    <td>{{ $log->new_status }}</td>
                    <td>{{ $log->updatedBy ? $log->updatedBy->name : 'System' }}</td>
                    <td>{{ $log->remarks ?? '-' }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @else
        <p style="font-style: italic; color: #666;">No history available for this document.</p>
        @endif
    </div>
    
    <div class="footer">
        <p>This report was generated by LGU Document Tracking System</p>
        <p>Document Number: {{ $document->document_number }}</p>
    </div>
</body>
</html>

